### ISSUE TITLE
Wiki section

### ISSUE THREAD

**Issue by lars18th** [akosinov/unicable#1]
Hi @akosinov ,

Please, open the Wiki section for explaining how to use the different tools. At time, your effort is awesome. However, for a lot of people this project is useless without a guide.

Thank you!

**Comment by akosinov** [comment]
it depends what u want :-) see wiki

**Comment by lars18th** [comment]
Hi @akosinov ,

Great! :smile: You done it! :+1: 

If you can, please add to this wiki the list of tested devices. I feel it will be useful if each user writes here about success (or failures) in programming different devices.

**Comment by akosinov** [comment]
done w tested equipment

**Comment by lars18th** [comment]
Perfect! :+1:
