### ISSUE TITLE
dsqsend: DiSeqC limit

### ISSUE THREAD

**Issue by lars18th** [akosinov/unicable#3]
Hi @akosinov ,

This tool is a must have. And using the provided "dconv" we can program without use special hardware. 

Regarding the limit of 6 DiSeqC buffer, I see this in the Linux header `<linux/dvb/frontend.h>`

```
struct dvb_diseqc_master_cmd {
	__u8 msg [6];	/*  { framing, address, command, data [3] } */
	__u8 msg_len;	/*  valid values are 3...6  */
};
```

So, if fact the number of bytes for each command are only three (3). Any sequence has three initial bytes of FRAME, ADDR and CMD... and after 0, 1, 2 or 3 bytes for data.

Then if this is right, then we need to use `dconv -l 6` or `dconv -l 3` ?

**Comment by akosinov** [comment]
And yes and no.
linux hardware and API has a limit of diseqc cmd length is 6 - you are right
but Unicable II specification violate old diseqc specification and use 7x framing bytes for it.
data send sequence within programming process is 7F 10 xx xx xx xx ..... so, we can send 4 bytes a time

**Comment by akosinov** [comment]
spliting of original files can be done by dconv w.  -l 6 option, where 6 is maximum diseqc sequence length

**Comment by akosinov** [comment]
just use `dconv -i <filename> -it <dsq or bin> -l 6` to see complete programming sequence on console
