### ISSUE TITLE
dconv: Binary version

### ISSUE THREAD

**Issue by lars18th** [akosinov/unicable#4]
Hi @akosinov ,

For some users it will be more simple to have a binary static version of the "dconv" tool.
You can compile it for example for x64 Linux using this technique:
http://blog.wrouesnel.com/articles/Totally%20static%20Go%20builds/

If you share static binaries in the "release" section it will be great!

**Comment by akosinov** [comment]
I'm never distribute any binaries, because all people has different systems w different libs, APIs and so on. compilation is very easy process.
