### ISSUE TITLE
using dconv on Linux with option -o created file without standard file permissions

### ISSUE THREAD

**Issue by hpingel** [akosinov/unicable#5]
Hi akosinov,

Thank you for your hard work on this project. I'm currently starting to test your tools on Ubuntu 16.04.
The issue I want to report is more an inconvenience than a bug.

I used dconv with option -o and found that the file created lacks any standard file permissions (like 664). 
When I call dconv with > file.dsq it works as expected.

No big deal, just wanted to point this out.

Cheers,
hepi

**Comment by akosinov** [comment]
Thanx for testing & reporting. Fixed.
