### ISSUE TITLE
Is it functional?

### ISSUE THREAD

**Issue by marian3** [akosinov/unicable#7]
I was trying to reprogram the inverto 32 band lnb, but without success (sat. position, or pin).
I have skystar usb 2 HD CI (driver stb0899).
Do you akosinov it works?

**Comment by marian3** [comment]
It seems that programming through PC sat. the card will probably go. It was necessary to modify the senddsq and when programming it is necessary to give LNB extra power (maybe not, but I have it over a long coax), eg through the splitter connect some stb and set the voltage mode to 13V.

This adjustment consists in switching (before the dissection of the sequences itself) to 18V (analogue from the sources of the lnb tune-18V-> cmd-> 13V):
...
int dsend(int fd, char *data) {
	struct timespec req = { 0, 1000000 * 100 };
	struct dvb_diseqc_master_cmd cmd;
	cmd.msg_len = 0;
	int p = 0, processed;
	unsigned char d;
  
    
  if(ioctl(fd, FE_SET_VOLTAGE, SEC_VOLTAGE_18))	{
			printf("problem Setting the Voltage\n");
			return -1;
}

usleep(100000);

while(sscanf(&data[p], "%02hhx %n", &d, &processed) == 1) {
...
after programming, do not forget to reset lnb - disconnect from all voltages.

Edit:
Still a small modification, which does not need to be connected through a 13V spliter (so extra power does not need, only 13V-> 18V edge):
...
if (ioctl(fd, FE_SET_TONE, SEC_TONE_OFF)) {
		printf("Setting tone error\n");
		return -1;
	}
  
  if(ioctl(fd, FE_SET_VOLTAGE, SEC_VOLTAGE_13))	{
			printf("problem Setting the Voltage\n");
			return -1;
}

usleep(2000000);  
	
	while(fgets(buf, sizeof(buf), in) && (!dsend(fd, buf))) {
...

**Comment by lars18th** [comment]
Hi @marian3 ,

If found a bug or an update, then please put a patch (PR section). I'm sure other users will appreciate it, as not all environments are equal.

Regards.

**Comment by marian3** [comment]
I am not a programmer and I am not orientated at all in the git environment.

Thanks for you work.


Dňa 8.10.2018 o 8:32 lars18th napísal(a):
> If found a bug or an update, then please put a patch (PR section). I'm 
> sure other users will appreciate it, as not all environments are equal.

**Comment by lars18th** [comment]
Tahnk you @marian3 for reporting your feedback.

I hope @akosinov will review your post and improves this project.

**Comment by marian3** [comment]
I can only confirm the functionality:
- progr. sat. positions
- progr. PIN
- progr. "static mode"

Inverto boys do not seem to be doing the heavy head and do not get any "traps" to thank them for.
At a little bit of effort programming via PC sat. the card could be incorporated into their UCIIP even though I understand that this is easier for them because they have their own programmer and do not have to deal with any incompatibility.
